### PR TITLE
#294 add settings to let admins select other macros that should be convert to MMC

### PR DESCRIPTION
**Pull request by khanguyen88**
Screenshot 2022-12-16 at 5 29 54 PM

### CODE REVIEW

**Comment by khanguyen88** [comment]
@boris-moduscreate please see the screenshot for the new settings controlling macros that will be converted

**Comment by boris-moduscreate** [comment]
@khanguyen88 rather than tying it to a migration, maybe we can just make it a thing they can run whenever? I expect this to be a general purpose "importer" long term. Imagine this scenario:

- Customer uses another app that provides a markdown macro
- Customer decides they want to use our diagram macro
- Customer is now paying for 2 markdown macros
- We support them migrating over to ours

**Comment by khanguyen88** [comment]
Oh I see your point. So we'll build a server-side "importer" that will convert selected macros to ours. This runs exclusively on the server side, and once it finishes, we can migrate the converted macros to Cloud without any change on the migration listener.

**Comment by boris-moduscreate** [comment]
No, this should be done 100% cloud side. Nothing should be processed server side.

**Comment by khanguyen88** [comment]
Ok gotcha. So we'll look at converting on the Cloud side only:
- Have a screen that displays 3rd party Macros we can migrate
- Let users select them
- Migrate to ours

**Review by nhan-nguyen-se — APPROVED** [review]

**Comment by boris-moduscreate** [comment]
@khanguyen88 yup that sounds right.

For better UX we may want to show some kind of % progress as I expect this can be a long running job. Maybe we do it based on the # of pages we have checked vs total pages on a system? or if we can't get total number of pages, maybe we use spaces?

**Pull request closed without merging**
