### PR TITLE
Relative paths for Azure DevOps support

### PR DESCRIPTION
**Pull request by DeagleGross**
If user wants to use any relative to markdown paths it is possible to check 'Render relative-path links to AzureDevOps repository' and write down full link to root of DevOps repository
image

The links combine as system files are doing it.
For example markdown can be placed at '?path=%2Finfrastructure%2Ftest%2F!README.md' (**\infrastructure\test\README.md**) and in markdown there is a relative link **(./UI)**.
So pathCombine should be **\infrastructure\test\UI**.

Paths would be combined and final link would be something like this:
<url-to-root-of-repository>?path=combine(markdownPath, url)

### CODE REVIEW

**Comment by bberenberg** [comment]
I am not sure if I understand the use case here because I don't use Azure DevOps. Could you provide a couple example markdown files with which I can see how this should work? You can place them in the testing folder of this repo on this branch.

Also, can this be presented to users in a non Azure specific manner? Something along the lines of "Override automatic relative path building"?

**Comment by DeagleGross** [comment]
Thanks for your reply!

The case is similar to what is implemented in github. In your [markdown-test-file.md](https://github.com/Atlas-Authority/MarkdownMacro/blob/master/testing/markdown-test-file.md#links) there is a relative-link example: *relative link, gitub](../README.md)*.

In github paths from root of repository to the file is defined in a such way: *github.com/**directory1/directory2/directory3/file.txt***
In Azure DevOps it is a little bit different: *devops.com/tfs/project/_git/reponame/**?path=\directory1\directory2\directory3\file.txt***
So if the checkbox is selected by user, I've implemented extracting path to imported file (it is defined in '?path=....' part of URL) and building such a link (by combining relative link path and imported file path) to azure devops repository.

For experiencing behaviour it is needed to use an azure devops server and having a repository there.
Let me show how this works in some screenshots:
- Firstly users define link to their own repository in azure devops (in description of field there is a hint how to do it):
image
- The link to raw-content of markdown in azure devops repository is written down. As you can see there is a *?path=* property in URL
image
- In the markdown file there is a relative link from README.md to some directory:
image
- This is a page URL where user is redirected after clicking the link. Final url consists of combined paths.
image


Thanks for suggestion, but I think that it is crucial to leave such a specific name for that parameter because as we see there are plenty of ways how different repositories are defining paths to files. The most obvious and useable definition is already implemented by yourselves (relative path support as in github repositories), however it can be confusing for some users trying to get relative link working in their custom case, when they are not using azure devops.

**Comment by bberenberg** [comment]
Ok so I went ahead and set up https://dev.azure.com/boris0014/_git/markdown-test?path=%2Ffolder%2Fsubfile.md which seems to demonstrate what you are talking about. Will there be other Azure specific configuration items you may want to add? Can the base URL be programmatically extracted from the URL provided to the Markdown file itself? Based on the portions you blacked out in your screenshot, I think yes?

**Comment by DeagleGross** [comment]
Great to hear You've tried the feature!

There are no specific configuration items needed for this feature anymore.

The second parameter I've added called 'Link to Azure DevOps Repository' is the link to root of repository. It will be concatenated with path in repository programatically.

This is done in this way because there are some different versions of Azure DevOps: older TFS 2013, 2015, 2017 (that were renamed to DevOps), Azure DevOps Server 2019 and Azure DevOps Services. All of them have different url-styling for accessing files. So I've left the responsibility to provide link to root of repository for user. In other cases URL could be parsed incorrectly.

**Comment by bberenberg** [comment]
Can we set the path field to be hidden until the Azure checkbox is enabled? I want to keep the UX as simple as possible for non azure users.

**Comment by bberenberg** [comment]
@DeagleGross Let me know if you can make this change, since #23 is merged and #20 is resolved, I would like to get this released ASAP.

**Comment by DeagleGross** [comment]
@bberenberg, I am trying my best to implement it ASAP. There is another workaround I've come up with: we can leave only string field for link to azure repo. If it is empty or whitespace, former logic would work. Otherwise new feature will be working. This workaround gets rid of 2 parameters for end-users. 

If You are okay with this, I can implement this logic very soon (in ~15 hours)  and new plugin version will be released.

Please, let me know Your thoughts on this. Sorry for a little delay in development

**Comment by bberenberg** [comment]
That is fine with me. Let's name the parameter:
> Base URL for AzureDevOps

With the help text of:
> If you are using AzureDevOps, configuring this value fixes relative links. Eg: https://azure-domain/tfs/project/_git/repo

**Comment by DeagleGross** [comment]
I've implemented logic using only base-url parameter.
Thanks for naming advice - I like it a lot!

Whitelist is a good idea. I am not experienced in developing atlassian plugins, so if You want to make a fast release, I am not sure I could implement it fast. To be honest, team I am working with likes Your plugin very much and will be contributing some more features soon. We could study documentation about whitelist or other possibilities and include that logic in later commits.

**Comment by bberenberg** [comment]
So we have a global config section at https://github.com/Atlas-Authority/MarkdownMacro/blob/master/src/main/resources/markdown-macro-config.vm 
Which connects to https://github.com/Atlas-Authority/MarkdownMacro/tree/master/src/main/java/com/atlassian/plugins/confluence/markdown/configuration
And then you can use the logic from https://developer.atlassian.com/server/confluence/including-information-in-your-macro-for-the-macro-browser/ to hide or show the parameter.

We're going to release 1.6.1. without this PR in it because I would rather get this right. And in the meantime, I believe your team already has this working right?

**Comment by DeagleGross** [comment]
Hello again!
Finally I've succeeded in implementing showing and hiding parameters based on global-config section. Sorry for taking such a long time.

I am making rest-api request and getting value 'isAzureDevOpsEnabled' from .js code right before rendering macro-edit page.
Looking forward to Your feedback :)

**Comment by bberenberg** [comment]
Hmm the latest code seems to not build for me?
```[INFO] --- confluence-maven-plugin:8.0.0:compress-resources (default-compress-resources) @ confluence-markdown-macro ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling javascript using YUI
[ERROR] invalid property id
	        boolean: {
[ERROR] syntax error
	        boolean: {
[ERROR] syntax error
	            "UseAzureDevOpsRelativePathUrls": function (param) {
[ERROR] syntax error
	            }
[ERROR] syntax error
	    }
[ERROR] syntax error
	});
[ERROR] Compilation produced 6 syntax errors.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.177 s
[INFO] Finished at: 2020-07-20T13:11:20-04:00
[INFO] ------------------------------------------------------------------------
```

Am I overlooking something?

**Comment by DeusDeorum1** [comment]
@bberenberg I believe that`s because of this ticket https://github.com/yui/yuicompressor/issues/262
The error occurs only during the first compilation of the project after changing js files. The next one usually goes without any problem.

**Comment by bberenberg** [comment]
That is odd but good to know. I can't get this to work, the option is always shown. Tested on Safari and Firefox. 
2020-07-20 at 3 35 PM

I also don't see any requests happening in the network tab that could be related, nor any errors in the browser console.

Also, with this new design, we can remove this checkbox entirely:
2020-07-20 at 3 41 PM

**Comment by DeagleGross** [comment]
@DeusDeorum1 thanks for issue link, I've added compressing js, css and resources to pom.xml. After that I've ran command 'atlas clean' and then my project compiled on the first try.

@bberenberg sorry, I've forgot to insert code in atlassian-plugin.xml that defines extra .js file for rendering and rest-api protocol for markdown-from-url. Can You, please, try it now?

**Comment by bberenberg** [comment]
@DeagleGross confirmed that the option is now being enabled and disabled as expected. Can you remove the checkbox and use the text field itself?

Also, I tried adding a bogus value to break it, but the relative images still loaded. Is the logic smart enough to fallback intelligently or is it not working?
2020-07-20 at 6 36 PM

**Comment by DeagleGross** [comment]
Happy to hear it is working!

I was thinking about these fields: in my opinion only 1 field is not so user-friendly. For example, I can implement using azure if in 'base URL field' there is not a whitespace string. Then lets imagine some user accidently places some random symbol in the field like '.' or etc. I wont be able to show any user-friendly message for this error. 
But this style is very intuitive - turn on the checkbox and fill the base URL field.
What do You think?

Relative links are not breaking markdown render when invalid URL is passed. Relative images are not expected to be processed through this extension so my college @DeusDeorum1 is working on this.

**Comment by bberenberg** [comment]
The relative link in my test was not adjusted either. I tried it with _https://azure-domain/tfs/project/_git/repo_ as the field value. So it seems like the core feature is not working yet. I don't mean to be rude here but could your team please do a bit deeper testing on your end? I seem to be finding very high level issues in what is supposed to be a finished PR.

**Comment by DeagleGross** [comment]
Sorry for taking such a long time in making this PR work.
Due to implementation difficulties I've forgot that a lof of link-styles could be used (before I was testing only '.\src'). So I deleted a restriction - now your relative link  (..\README.md) works correctly.

**Rendered markdown:**
image

**Resolved path:**
image

**Comment by bberenberg** [comment]
Checking the box and not entering a value like this:
2020-07-22 at 9 46 PM
results in the entire Macro breaking. 

Can we take the approach of the text field being empty meaning that this is disabled without also having the checkbox?

We also need to add headers to the main config page to create some degree of visual separation between the configuration sections. 

I also noticed that if I:

1. Enable Azure globally
2. Configure a macro using this functionality
3. Disable Azure globally

The macro will continue to use the Azure functionality which means you're not checking the configuration value at runtime.

**Comment by DeagleGross** [comment]
Changes:
- frontend change on config page
image

- for better experience I've turned off visibility of names and values of plugin-parameters in edit-view
image

- implemented logic with only string field for link to azure dev ops
image

- after enabling, setting up, disabling azureDevOps render now in runtime in class MarkdownFromUrlMacro there is an additional check for config the same as with the whitelist. So page rerenders correctly with changed global config setting.

**Comment by bberenberg** [comment]
This has been released as 1.6.2 on the Marketplace

**Pull request merged**
