### PR TITLE
Release to marketplace

### LINKED ISSUE #58: Automate listing new app version on marketplace
Enhance release action so that we can automate listing new app version on Atlassian Marketplace.

Here is the official instruction https://developer.atlassian.com/platform/marketplace/listing-an-app-version-using-rest/

cc: @bberenberg

### PR DESCRIPTION
**Pull request by nhan-nguyen-se**
Close #58 

@bberenberg 

I just created this DRAFT PR for easy discuss. Automating marketplace release is more complex than we think. Basically we need to:
1. upload jar file to marketplace and get back the download link
2. create new app version with that download link
3. bump migration required version

(Please check this [link](https://developer.atlassian.com/platform/marketplace/listing-an-app-version-using-rest/) for full steps.)

For step 1 I can't find an action on GitHub Marketplace to do it. There are many http client action out there but all of them using `multipart/form-data` content type. Atlassian requires `application/octet-stream`. So I have to fork a [repo](https://github.com/nhan-nguyen-se/http-request-action) and make some changes to fit with our needs. Let me know if it is OK and:
- I should move it to Atlas-Authority org
- I should contribute an PR back to the upstream. It requires extra time to work on (update their docs and unit test)

I'm a bit concern because I can't test it the whole. There are 3 APIs require authentication. For those APIs which does not requires auth I tested them already.

### CODE REVIEW

**Comment by bberenberg** [comment]
Yes let's transfer the repo to Atlas Authority.
Then yes we should make a PR to the upstream.

Do you want to make a new dummy app in Java and I can create a marketplace listing for testing? We can use an app key like com.atlasauthority.marketplace.test 

This tutorial seems the easiest to use https://bitbucket.org/atlassian_tutorial/confluence-v2-search-query-tutorial/src/0f8dfbcb9b286bcbbfc3fc389b462d194aba2633/?at=issue%2FCONFSRVDEV-10232-confluence-7

**Comment by nhan-nguyen-se** [comment]
Yep. It would be great if we can have a dummy app to test Marketplace API.

**Comment by bberenberg** [comment]
You can test at https://github.com/Atlas-Authority/example-confluence-server-app Let me know if you need anything more.

**Comment by nhan-nguyen-se** [comment]
PR to upstream created https://github.com/fjogeleit/http-request-action/pull/37

**Review by khanguyen88 — CHANGES_REQUESTED** [review]
we should lock action version to a specific commit rather than using ``@master`` to avoid unintended breaking change from upstream. Eg: ``fjogeleit/http-request-action@master``

**Comment by nhan-nguyen-se** [comment]
Fixed by using fixed tag

**Review by khanguyen88 — APPROVED** [review]

**Pull request merged**
