### PR TITLE
Replaced minified version with latest, may need to drop related css file

### PR DESCRIPTION
**Pull request by boris-moduscreate**
@khanguyen88 Trying to bump the code to handle #86 
Since the new file has inline CSS I guess the v9 version removes the CSS dependency? 
Also not seeing a v10.x minified version direct from vendor?

### CODE REVIEW

**Comment by khanguyen88** [comment]
we just need to replace the JS file with content from this URL https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs

Guide: https://mermaid.js.org/intro/n00b-gettingStarted.html#_3-calling-the-javascript-api

**Comment by boris-moduscreate** [comment]
Hmm weird, and the v10 version doesn't have the inline CSS again. I guess I can make a release and have the automation build a version for me to test with then delete the version and re-release when it's validated?

**Comment by khanguyen88** [comment]
hold on, upon closer look, I think it will be fairly involved to upgrade to v10.

Some background:
Jira's web resource manager does not yet support ESM format, which v10 is using ([link](https://community.developer.atlassian.com/t/how-to-import-javascript-modules-from-web-resource/43237/2))
The last version to still have the ``.min`` file which will work nicely with Jira is [9.4.3](https://cdn.jsdelivr.net/npm/mermaid@9.4.3/dist/). Does this version have what we want?

**Comment by boris-moduscreate** [comment]
I think they do, yes.

**Comment by boris-moduscreate** [comment]
@khanguyen88 ok I changed it back to 9.4.3.

**Pull request merged**
