### PR TITLE
add support Footnotes

### PR DESCRIPTION
**Pull request by sparksparrow**
Add support Foonotes in AzureDevOps repository. 
Main logic has been added [here](https://github.com/Atlas-Authority/MarkdownMacro/pull/22).

### CODE REVIEW

**Comment by bberenberg** [comment]
@sdegutis do you see any issues with this? Seems fine to me.

**Review by sdegutis — APPROVED** [review]
Looks fine.

**Comment by bberenberg** [comment]
@sparksparrow FYI, I don't think we will create a dedicated release for this. This will go out in whatever the next release in general will be. My guess is that will be tied to upcoming bug fixes related to automated migrations with Confluence Cloud Migration Assistant.

**Comment by sparksparrow** [comment]
@bberenberg Thanks for the information. If possible, could you please guess approximately when we can see the release?

**Comment by bberenberg** [comment]
I would say a few weeks seems to be where we're headed? Not sure to be honest. You can compile it and run your own build in the meantime though? Just set a reminder to check back in a month and pull the latest version from the Marketplace to ensure you get future updates.

**Comment by sparksparrow** [comment]
Great, thanks for the advices, I'll be waiting for the release.

**Comment by bberenberg** [comment]
Looks like you got lucky and #51 is causing an urgent release, this should be out shortly.

**Comment by sparksparrow** [comment]
Great, thanks.

**Pull request merged**
