### PR TITLE
Fix deps issue

### LINKED ISSUE #72: 1.6.17 release doesn't enable on Confluence
Throws the following:

```
2022-08-18 13:43:40,913 ERROR [ThreadPoolAsyncTaskExecutor::Thread 38] [internal.dependencies.startup.DependencyWaiterApplicationContextExecutor] fail Unable to create application context for [com.atlassian.plugins.confluence.markdown.confluence-markdown-macro], unsatisfied dependencies: none
 -- url: /confluence/rest/plugins/1.0/ | referer: https://lab.remote-desktop.org/confluence/plugins/servlet/upm/marketplace/search?q=markdown | traceId: 3e89b7cc725fa7fb | userName: admin
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'migrationListener': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.atlassian.plugins.confluence.markdown.ccma.MigrationListener] from ClassLoader [com.atlassian.plugins.confluence.markdown.confluence-markdown-macro [315]]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:57)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:322)
	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:287)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.atlassian.plugins.confluence.markdown.ccma.MigrationListener] from ClassLoader [com.atlassian.plugins.confluence.markdown.confluence-markdown-macro [315]]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267)
	... 18 more
Caused by: java.lang.LinkageError: loader constraint violation: loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @38ad5f65 wants to load interface com.atlassian.migration.app.gateway.AppCloudMigrationGateway. A different interface with the same name was previously loaded by org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @134b02c4. (com.atlassian.migration.app.gateway.AppCloudMigrationGateway is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @134b02c4, parent loader org.apache.catalina.loader.ParallelWebappClassLoader @609ed3d4)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2410)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2194)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1607)
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
	... 20 more
```

Reproduced on lab, and caused an issue at:
https://atlasauthority.atlassian.net/browse/SUPPORT-1770
https://atlasauthority.atlassian.net/browse/SUPPORT-1774
https://atlasauthority.atlassian.net/browse/SUPPORT-1781

We have pulled the 1.6.17 release from marketplace entirely as a result.

### PR DESCRIPTION
**Pull request by nhan-nguyen-se**
Fixes #72

### CODE REVIEW

**Review by khanguyen88 — APPROVED** [review]

**Comment by boris-moduscreate** [comment]
I still don't understand why this broke for multiple people in 1.6.17 when there were no changes related to this between 1.6.16 and 1.6.17: https://github.com/Atlas-Authority/MarkdownMacro/compare/a6d880ae5f2e5fe58ddfa1873349d7dbfb06dd28...02a70037d3662c0b074da4f029618af08369903b

This feels wrong, and my concern is that this will break again for another subset of customers.

**Comment by nhan-nguyen-se** [comment]
There are two changes related to bean/dependency injection in the last release:
- autowire CQLSearchService
- renamed bean MyPluginComponent to MigrationListener

But I'm not sure if these changes has something to do with OSGI dependency resolving.

**Comment by nhan-nguyen-se** [comment]
I notice there is iframes-for-confluence 1.6.12 installed on remote lab. That version and markdown macro 1.6.16 both export `com.atlassian.migration.app.listener` which may conflict. Also, iframes-for-confluence 1.6.12 has issue with dependencies (I cannot install it on my local system).

**Comment by boris-moduscreate** [comment]
Do these same changed need to be made on the Iframes for Confluence side?

**Comment by nhan-nguyen-se** [comment]
@boris-moduscreate No. It doesn't. I and @khanguyen88 have refactored dependency injection stuffs in iframes-for-confluence 1.6.17 and it fixes this issue as well.

**Pull request merged**
